<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Login_Login_logo__xLtTr</name>
   <tag></tag>
   <elementGuidId>f69b06db-7edb-47b8-bc20-a8ff2b1ffdb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.Login_logo__xLtTr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>82bcbf70-6841-4436-b990-fafa6a237f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Login_logo__xLtTr</value>
      <webElementGuid>4e1aa1ae-227c-44bf-8c11-e37ac7c9e857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/logo-astra.b80ff6876c81947fd1432dccdc82a659.svg</value>
      <webElementGuid>7e21eeb9-b250-405c-9abb-6fd08fbc1dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>d4299a00-5121-42b5-8053-d801f34af593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;Login_wrapper__Ppc8E&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-xs-24 ant-col-sm-8 ant-col-md-8 ant-col-lg-8&quot;]/img[@class=&quot;Login_logo__xLtTr&quot;]</value>
      <webElementGuid>09ffe1a1-2c7b-4545-9eec-5fbb0408ef8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/img</value>
      <webElementGuid>6a2a1ee9-94b8-49ce-9241-4856eb61408b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>af8f38f2-c5f2-479e-a966-adb85eca0be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>8592b0d5-4448-4e45-8408-05f268bea27a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/logo-astra.b80ff6876c81947fd1432dccdc82a659.svg' and @alt = 'logo']</value>
      <webElementGuid>9f4e4031-a389-4490-8c42-c2058fd18410</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
