<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__LogoSign</name>
   <tag></tag>
   <elementGuidId>76848af8-9a57-4938-bf0d-2c09e8a057c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.LogoSign</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>233c973f-5ca5-49de-a10d-5b8680fe6f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LogoSign</value>
      <webElementGuid>902eddb1-ba90-4231-a539-9b7bc8518dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-bwzfXH lfzKet isoSignInPage&quot;]/div[@class=&quot;isoLoginContentWrapper&quot;]/div[@class=&quot;isoLoginContent&quot;]/div[@class=&quot;isoLogoWrapper&quot;]/a[1]/div[@class=&quot;LogoSign&quot;]</value>
      <webElementGuid>55a5d4d7-9ab3-4844-a28f-769375e1b257</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/a/div</value>
      <webElementGuid>4794c7d1-95d0-4d5d-aa8d-88cd7667c82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>a774eb34-fced-4dd0-9462-5349dc5ddde5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
